import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "../components/SideNav";
import Header from "../components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tech Market Place",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div>
          <div className='sm:w-64  sm:block fixed'>
              <SideNav />
          </div>
          <div className='md:ml-64'>
              <Header />
              {children}
          </div>
        </div>

      </body>
    </html>
  );
}
